### ISSUE TITLE
Connection reset by peer - SSL_connect (Errno::ECONNRESET)

### ISSUE THREAD

**Issue by dongtong** [gimite/google-spreadsheet-ruby#14]
HI gimite
   When i connect google doc, it reports "ruby-1.8.7-p302/lib/ruby/1.8/net/http.rb:586:in `connect': Connection reset by peer - SSL_connect (Errno::ECONNRESET)"
Do you know why?
Thanks

**Comment by zhizouxiao** [comment]
@dongtong I get the same problem, because I'm in China. and I get the solution. https://ruby.taobao.org/
